### ISSUE TITLE
[EPIC]: Feedback UI preview3

### ISSUE THREAD

**Issue by zyronix** [hashtopolis/server#1036]
### Description

Hashlist page
 - [x] New hashlist page not working
 - [x] Once you have click on new hashlist you cannot get back the the hashlist overview without reloading the page.
 - [x] http://127.0.0.1:4200/#/hashlists/hashes/hashlists/1 does not show the hash 
![image](https://github.com/hashtopolis/server/assets/4386076/160733d2-728a-4b16-8d99-8e7d8469f76b)
 - [x] Cannot update the isSecret flag flag from the edit page, getting error:  Key 'notes' is not of type string 

Task
 - [x] New task create screen looks like the hashlists is a multi selector?
 - [x] Taskover view page should sort by default on task priority 
![image](https://github.com/hashtopolis/server/assets/4386076/ccf53aec-776b-44dc-9991-78253857a80b)
 - [x] From task overview the copy to task does not copy the hashlistid
 - [x] Visual bar bigger then screen width when setting UI setting to max width
![image](https://github.com/hashtopolis/server/assets/4386076/46ed30f4-6c93-4947-add8-6297d8da6e22)
 - [ ] When you change the sorting of a table, it is not saved. If you move back to the page after viewing another page it does not keep the sorting -> Depends on https://github.com/hashtopolis/server/issues/1097

Supertask
 - [x] Edit Supertask Missing runtime calculation, overall working but not value for each row in table

New Agent
 - [x] When you have create a voucher, you cannot see the voucher value anymore. 
![image](https://github.com/hashtopolis/server/assets/4386076/2b486fca-9ca8-4b25-8b56-b11025845cdf)
- [x] There is no easy to copy download url, somewhere on the binary I want to have a copy this path link to download: http://localhost:8080/agents.php?download=1 (check the old UI)
![image](https://github.com/hashtopolis/server/assets/4386076/b2346998-11d0-4c27-a663-e0208516cf05)

Config
 - [x] Header style inconsistent with rest of the style. Use similar style to 'new agent' maybe?
 - [x] Notification page of config consistent with other page, like that style, but if you have the space make it possible to place two of those groups together.

Backend API errors
 - [ ] **Task expand hashlist** doesnt return hashlist array, it was working before. Urgent. Affects copy tasks and edit tasks
 - [x] **Assign agents delete** doesnt work
       Assign and unsasign agents to tasks works
 - [x] Import supertasks, all page missing
       Import supertasks page is already available
 - [x] #1113
