### ISSUE TITLE
[EPIC] Docker installation

### ISSUE THREAD

**Issue by zyronix** [hashtopolis/server#723]
For now when creating a container it is not possible to to automate the creation of the user and import the default database structure. A solution for this can be to extend the install.php file with commandline options to automate this.

The purpose of these changes is to facilitate the setup of Hashtopolis with Docker and allow more flexibility in configuration.
So far when installing Hashtopolis, even with Docker, the Installation steps needed to be completed to let it set up the database and create an initial user. With the upcoming changes to the backend the manual setup of a server gets more and more complicated why using Docker gets recommended. 
Typically, when Hashtopolis should be set up, all the required information should already be present, so there is not really a need to have some click-through installation, but instead it can just be completely automatically. This is the purpose of this pull request. Either the database connection details can be set in the old conf.php file format or it can be passed in a docker compose via environment variables.

While we strongly recommend to switch to a docker setup in the future, we understand that there still may be users which prefer to run Hashtopolis directly on a server. The same for setups which are already existing which should not be affected by the changes, they should be updated just as usual without having to manually interact with it. 

A side effect of this installation procedure changes is the restructuring of the data directories. In order to better separate them from the source code, the path for these can now be configured and can be mounted inside docker without having to create three mount binds.

As this is a fairly complex change, we need to make sure that all use-cases can still run properly and will not break existing installations. Further some documentation updates will also be required so people understand what the new possibilities for installation are.

- [x] Write installation documentation how to install with Docker.
- [x] Write installation documentation how to install without Docker.
- [X] Test use-case 1: Fresh setup with Docker.
- [x] Test use-case 2: Upgrade existing Docker setup.
- [x] Test use-case 3: Upgrade existing Docker setup with changing directory structure.
- [x] Test use-case 4: Fresh setup without Docker (using the conf.php.template).
- [X] Test use-case 5: Upgrade an existing setup running without Docker (via git pull).
- [x] Test use-case 6: Continue running a non-docker setup without setting up anything of apiv2.
- [x] Add new devcontainer config to use the new docker image
- [x] Test downloading repo as zip (maybe git stuff is broken)
- [x] Fix updates, still uses conf.php
- [x] Fix tests, still uses conf.php

**Comment by zyronix** [comment]
When upgrading from old config I get the following error:

```hashtopolis  | [Fri May 12 08:46:03.567117 2023] [php:warn] [pid 20] [client 172.18.0.1:43272] PHP Warning:  file_put_contents(/var/www/html/inc/../config//pepper.json): Failed to open stream: No such file or directory in /var/www/html/inc/load.php on line 33
hashtopolis  | [Fri May 12 08:46:30.879786 2023] [php:warn] [pid 20] [client 172.18.0.1:43272] PHP Warning:  file_get_contents(/var/www/html/inc/../config//pepper.json): Failed to open stream: No such file or directory in /var/www/html/inc/load.php on line 182```
