### ISSUE TITLE
[EPIC] [PLACEHOLDER] Implement missing API calls

### ISSUE THREAD

**Issue by zyronix** [hashtopolis/server#854]
# Urgent
 - [x] [API] Hashlists are missing related tasks objects 
 - [x] [API] Task expanding files
 - [x] [API] Task expanding hashlist
 - [x] [API] When creating task with a hashtype other then 0, the hashtype becomes 0
 - [x] [API] Show archived is not working
 - [x] [API] isCracked filtering broken
 - [x] [API] Tasks expand Assign Agents
 - [x] [API] Edit agent, cracker error only false/true, but there are 3 options
 - [x] [API] Cracks, missing time cracked, agent, task info, hashtype, chunk, salt?
 - [x] [API] User API call "Member of Groups"
 - [x] [API] Method for Desc/Asc results
 - [x] [API] isSmall creating pretask is broken

 - [x] [API] Edit Agent Page - Option cracker Errors returns true or false but it is 3 options; deactivate agent on errors, keep agent running and discard errors. should be of type number  - @xbenyx 
 - [x] [API] Search Hash page - find multiple hashes - @xbenyx
 - [ ] [API] Hashlist and Superhaslist API call for pre-cracked buttons import and export - @xbenyx
 - [ ] [API] Hashlist expand task doesnt return any tasks. - @xbenyx 
 
 - [x] #903
 - [x] #859
 - [x] #906
 - [x] #855
 - [x] #857

**Comment by mercur1114** [comment]
Hasan pekyürek

**Comment by mercur1114** [comment]
> # Urgent
>  - [ ] #903
>  - [ ] #859
>  - [x] [API] Task API missing related hashlists
>  - [ ] #904
>  - [ ] #905
>  - [ ] #906
>  - [ ] [API] Renaming all id and name attributes to 'id' and 'name'
> 
> # Unknown
>  - [ ] #855
>  - [x] #856
>  - [ ] #857
>  - [ ] [API] Add HashType Tests
>  - [ ] [API] Add Hash Tests
>  - [ ] [API] Hashlists are missing related tasks objects
>  - [ ] [API] Users are missing related groups objects
>  - [ ] [API] Agent missing AccessGroup
>  - [x] #858
>  - [ ] [API] Add sorting to query parameterings per field and per order (IWant the last 100 chunks sorted by date)
>  - [ ] [API] ADd query parameter for the total amount of entries available for pagination _total
>  - [ ] [API] Improve performance of pagination, use LIMIT and RANGE in DBA model
>  - [ ] Improvement for dispatch time, currently requests all chunks to determine the progress

**Comment by rixvet** [comment]
>  [API] Cracks, missing time cracked, agent, task info, hashtype, chunk, salt?

Think this is already working:
```$ ./htcli.py list Hashlists --expand='hashes'```

**Comment by rixvet** [comment]
> [API] Boolean filtering not working for users API call, for example users.php?filter=isValid=true, should return all valid users

Think this is already working:
````$ ./htcli.py list HashTypes --filter isSalted=False```

**Comment by zyronix** [comment]
Release in 0.14.1
