### ISSUE TITLE
[EPIC] [API] New Permissions schema

### ISSUE THREAD

**Issue by zyronix** [hashtopolis/server#872]
With the new API there will come some changes to the permission schema.

The APIGroup/APIKey will be dropped.

The RightGroup will be used for settings permissions on the API. The RightGroup does not have all permissions yet for all objects.
Any object will always have:
- Create
- Read
- Update
- Delete

Permissions, for some objects (HashType) there is only Read permission. The BaseAPIModel should be extended with implementation of the permissions checking and those calls will do the permission checking use the same code of the old core.

Todo:
 - [x] Design permission schema
 - [x] Implement POC for first permission schema
 - [x] Implement all objects in the permission schema
 - [x] #856

**Comment by rixvet** [comment]
https://github.com/hashtopolis/server/blob/master/ci/apiv2/PERMISSIONS_REWORK.md could be used as inspiration as well.

**Comment by zyronix** [comment]
Release with 0.14.1
