### ISSUE TITLE
[EPIC] [PLACEHOLDER] Implement missing UI elements

### ISSUE THREAD

**Issue by zyronix** [hashtopolis/server#873]

**Comment by xbenyx** [comment]
Agents UI section completed. Green icon when agent is active and pause red icon when is inactive. Test it also in darkmode. 

![Image](https://github.com/hashtopolis/server/assets/13848557/ea38b231-23a9-4093-9b53-00feddd3e6b5)

**Comment by xbenyx** [comment]
- [x] When creating hashlist or task, once done redirect to task/hashlist page and not the new overview
- [x] Editing hashlist returns in an error, it tries to submit to /hashlists/undefined and not to for example /hashlists/53
- [x] Make it possible to click the hashlist name to get to the hashlist edit page

**Comment by xbenyx** [comment]
Tasks

 - [x] The ID's are not always shown correct, sometime the font seems to be white. ** That happens when the color is selected from the old ui, new UI defines color with # ** 
 - [x] Make the color icon square instead of roundish. **Removed the border radius and padding**
 - [x] Enable select row in any column. **We talked about this one.**

**Comment by xbenyx** [comment]
Hashlist

  - [ ] Add bulk action to the hashlist page
  - [x] Submitting hashes not working (missing base64) sourcedata

File

  - [ ]   Auto create file once uploading is completed. (remove the create button)

Other:

  - [ ]  Remove 'All: ...' from console
  - [ ]  When date is not changed, use default value to prevent date from being incorrect

**Comment by xbenyx** [comment]
- [ ] Add auto refresh button in Tasks, Hashlists and Files
