### ISSUE TITLE
[EPIC] SuperTask Improvements

### ISSUE THREAD

**Issue by zyronix** [hashtopolis/server#918]
Currently there are some improvements that can be made for SuperTasks. Those improvement will be made in the new UI / API.

For example the database is refering to TaskWrappers, a SuperTask is a SuperTask is the TaskType is set to '1'. If that is true then it is a supertasks.

 - [ ] Rename SuperTasks to SuperTaskTemplates
 - [ ] Rename Pretasks to TaskTemplates
 - [ ] #906 
 - [ ] Drop Rule splitting feature
 - [ ] Detail page for Supertask
 - [ ] Task table should also display SuperTasks

**Comment by ObsidianOracle** [comment]
Closed this ticket since we have smaller tickets for all subtickets.
