### ISSUE TITLE
[EPIC]: Testframe work for the UI

### ISSUE THREAD

**Issue by zyronix** [hashtopolis/server#984]
### Description

The new-ui doesn't have any testing framework. Currently testing is quite time consuming.

 - [ ] Create manual test plan
 - [ ] Research possible angular testframeworks (Karma? https://karma-runner.github.io/latest/index.html)
 - [ ] Implement initial tests

**Comment by xbenyx** [comment]
Currently the frontend has the files for the angular testing framework, in each file is possible to find a component.spec.ts. If you run an angular test these files will be fired but of course will crash as data needs to be mocked up, or actions for buttons. Some components are almost identical and can be reusable but even that requires some work using the Angular framework.
